version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '01:00'
      timezone: 'Europe/London'
    versioning-strategy: 'increase'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      vitejs:
        patterns:
          - '@vitejs/*'
          - '@svgr/*'
        update-types:
          - minor
          - patch
      vitejs-major:
        patterns:
          - '@vitejs/*'
          - '@svgr/*'
        update-types:
          - 'major'
      fastify:
        patterns:
          - '@fastify/*'
          - 'fastify*'
        update-types:
          - minor
          - patch
      fastify-major:
        patterns:
          - '@fastify/*'
          - 'fastify*'
        update-types:
          - 'major'
      eslint:
        patterns:
          - 'eslint*'
        update-types:
          - minor
          - patch
      eslint-major:
        patterns:
          - 'eslint*'
        update-types:
          - 'major'
      misc-scoped:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      misc-scoped-major:
        patterns:
          - '*'
        update-types:
          - 'major'
    open-pull-requests-limit: 20
