name: Dependabot Checks
on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-label:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Label Major
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        run: gh pr edit "$PR_URL" --add-label "semver:major"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label Minor
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr edit "$PR_URL" --add-label "semver:minor"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label Patch
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr edit "$PR_URL" --add-label "semver:patch"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependabot:
    needs: dependabot-label
    runs-on: ubuntu-24.04
    # if it's a pull request created by Dependabot
    if: github.actor == 'dependabot[bot]'

    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        id: merge-dependabot
        with:
          target: minor
          use-github-auto-merge: true
      - name: Print merge status
        run: |
          echo "Merge status: ${{ steps.merge-dependabot.outputs.merge_status }}"
