name: Dependabot Auto Merge

on:
  pull_request:
    branches:
      - 'main'

jobs:
  dependabot:
    runs-on: ubuntu-24.04
    # if it's a pull request created by Dependabot
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        id: merge-dependabot
        with:
          target: minor
          approve-only: true
          use-github-auto-merge: true
      - name: Print merge status
        run: |
          echo "Merge status: ${{ steps.merge-dependabot.outputs.merge_status }}"
